### PR TITLE
added fasthttp adapter

### PR DESCRIPTION
**Pull request by sneakykiwi**

### CODE REVIEW

**Review by sleeyax — CHANGES_REQUESTED** [review]
I purposefully put all adapters in their own modules under `examples` in order to keep the core gotcha lib small and unbloated. For example someone who installs gotcha and only uses adapter X doesn't need to install dependencies for adapter Y and Z as well. It should be up to the user to define adapter(s) according to their use case.

I'm not sure if adding all dependencies for adapters to the root module is the way to go. Perhaps we can build some kind of module system with adapters in separate repositories so users can install them separately. 

What do you think?

**Comment by sneakykiwi** [comment]
This sounds good, maybe we should rename the directory from `examples` to adapters and keep them as they are as submodules with their own go.mod.

**Comment by sleeyax** [comment]
Agreed, I was overthinking it a bit too much. We can add the adapters as submodules pegged to a specific version of gotcha within this repository like you suggest.

**Comment by sneakykiwi** [comment]
I've pushed an update earlier that initializes the adapters as modules while keeping the `examples` directory

**Pull request merged**
